name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Javascript
      uses: actions/javascript-action@v1

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Build
      run: |
        npm install
        npm run compile
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: logs
        path: .npm/_logs/*
        retention-days: 14

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Javascript
      uses: actions/javascript-action@v1

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Install
      run: |
        npm install

    - name: Tests
      run: |
        npm run test-core
        npm run test-generate
        npm run test-reports
      
    - name: Tests RPKI
      run: |
        rm -f -R .cache/
        ./node_modules/.bin/mocha --exit tests/rpki_tests/tests.default.js --require @babel/register
        ./node_modules/.bin/mocha --exit tests/rpki_tests/tests.external.js --require @babel/register
        rm -f -R .cache/ && ./node_modules/.bin/mocha --exit tests/rpki_tests/tests.external-roas.js --require @babel/register

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: logs
        path: .npm/_logs/*
        retention-days: 14